books/urls.py
from django.urls import path
from .import views

app_name = 'books'

urlpatterns = [
    path('', views.welcome, name='welcome'),
     #Librarian urls
    path('home/', views.Home, name="Home"),
    path('add_book/',views.add_book,name='add_book'),
    path('borrowed_books/',views.borrowed_books,name='borrowed_books'),
    path('requested_books/',views.requested_books,name='requested_books'),
    path('update_book/<id>',views.update_book,name='update_book'),
    path('delete_event/<id>',views.delete_book,name='delete_book'),
    path('search_books_librarian/', views.search_books_librarian, name="search_books_librarian"),
    path('book_librarian/<str:pk>/', views.book_librarian, name="book_librarian"),
    path('book_report', views.book_report, name="book_report"),
    path('view_requested_book/<int:id>/', views.Issue, name="view_requested_book"),
    #path('issue_book/', views.Issue_book, name="Issue_book"), 
     #student urls
    path('Home_student/',views.Home_student,name="Home_student"),
    path('payments_student/',views.payments_student,name='My_payments'),
    path('My_books/', views.my_book, name="My_books"),
    path('search_books/', views.search_books, name="search_books"),
    path('book_student/<str:pk>/', views.book_student, name="book_student"),
    path('book/<int:id>/', views.Borrow_book, name="borrow_book"),
    path('borrow_book/<int:id>/',views.Borrow,name='Borrow_page'),


    #path('index', views.index, name='index'),
]

library/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('books.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User


class Book(models.Model):

    class BookStatusChoices(models.TextChoices):
        AVAILABLE = "AVAILABLE", ("Available")
        UNAVAILABLE = "UNAVAILABLE", ("Unavailable")
        BOOKED = "BOOKED", ("Booked")

    book_title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    edition = models.CharField(max_length=255)
    Date_added = models.DateField(auto_now_add=True)
    subject_area = models.CharField(max_length=255)
    book_cover = models.ImageField(upload_to = 'images/')
    added_by=models.CharField(max_length=100,null=True,blank=True)
    date_updated=models.DateTimeField(auto_now=True)
    ISBN= models.CharField(null=True, blank= True,max_length=200)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, default="AVAILABLE", choices=BookStatusChoices.choices)
    def __str__(self):
        return self.book_title

    def delete(self,*args,**kwargs):
        self.book_cover.delete()
        super().delete(*args,**kwargs)    


class Borrowed_book(models.Model):

    class ReturnStatusChoices(models.TextChoices):
        BOOKED = "BOOKED", ("Booked")

    user=models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    date_borrowed=models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=15, default="BOOKED", choices=ReturnStatusChoices.choices) 


class Issued_book(models.Model):

    class ReturnStatusChoices(models.TextChoices):
        BOOKED = "BOOKED", ("Booked")
        TAKEN = "TAKEN", ("Taken")
        RETURNED = "RETURNED", ("Returned")

    user=models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    book = models.ForeignKey(Borrowed_book,on_delete=models.CASCADE)
    date_issued=models.DateTimeField(auto_now_add=True)
    return_date=models.DateTimeField(null=True)
    date_returned=models.DateTimeField(null=True)
    fine = models.IntegerField(null=True, blank=True)
    return_status = models.CharField(max_length=15, default="BOOKED", choices=ReturnStatusChoices.choices)

'''    def Fine_calc(self):
        Issued_book.return_date+=1
        days=Issued_book.date_returned - Issued_book.return_date
        if days>=3:
            return Issued_book.fine==5000

        elif days>=10:
            return Issued_book.fine==15000
        else:
            return Issued_book.fine==0 
        Issued_book.save()
'''

books/forms.py
from django import forms
from django.forms import ModelForm
from .models import Book,Issued_book


#create an add book form
class bookform(ModelForm):
    class Meta:
        model=Book
        fields=('book_title','description','ISBN','author','book_cover','added_by','edition','subject_area')

    def __init__(self,*args,**kwargs):
        super(bookform,self).__init__(*args,**kwargs)

        self.fields['book_title'].widget.attrs['class']='form-control'
        self.fields['description'].widget.attrs['class']='form-control'
        self.fields['author'].widget.attrs['class']='form-control'
        self.fields['book_cover'].widget.attrs['class']='form-control'
        self.fields['added_by'].widget.attrs['class']='form-control'
        self.fields['edition'].widget.attrs['class']='form-control'
        self.fields['subject_area'].widget.attrs['class']='form-control'

class Issue_book(ModelForm):
    class Meta:
        model=Issued_book
        fields=('user','book','return_date','fine','return_status')

 

books/views.py
from django.shortcuts import render, redirect
from .models import Book,Borrowed_book
from django.contrib.auth.models import User
from .forms import bookform,Issue_book
from django.http import HttpResponseRedirect
from django.contrib import messages
import datetime 
#import pdf stuff
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

#import paginator stuff
from django.core.paginator import Paginator

app_name = 'books'


def welcome(request):
    return render(request,'books/welcome_page.html')


#Student views
def my_book(request):
    context={}
    return render(request,'books/My_books.html',context) 


def payments_student(request):
    return render(request,'books/payments_student.html')


def Home_student(request):
    books=Book.objects.all().order_by('Date_added')
    #Setup pagination
    p=Paginator(Book.objects.all(),5)
    page=request.GET.get('page')
    books_list=p.get_page(page)
    pages="p"*books_list.paginator.num_pages
    context={'books':books,
    'books_list':books_list,
    'pages':pages}
    return render(request,'books/home_student.html',context)


def search_books(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        books = Book.objects.filter(book_title__contains=searched)
        return render(request,'books/search_books.html',
        {'searched':searched,
        'books':books})
    else:
        return render(request,'books/search_books.html')

def book_student(request, pk):
    book=Book.objects.get(id=pk)
    context = {'book': book}      
    return render(request,'books/book_student.html',context)

def Borrow(request,id):
    book = Book.objects.get(id=id)

    return render(request,'books/borrow_book.html',{
        'book': book,
        'book_id': id,
        'title': 'Borrow a Book'
    })

def Borrow_book(request,id):
    user_id=request.user.id
    book=Book.objects.get(id=id)
    b=Book.objects.all()
    if b.status =="AVAILABLE":
        b.status=='UNAVAILABLE'
        b.save()
    user=User.objects.get(id=user_id)
    borrowed_book=Borrowed_book.objects.create(user=user,book=book,fine=0,date_borrowed=datetime.datetime.now())
    borrowed_book.save()
    
    messages.info(request,("book was borrowed successfully...."))
    return redirect('books:Home_student')

#Librarian views
def Home(request):
    books=Book.objects.all().order_by('Date_added')
    #Setup pagination
    p=Paginator(Book.objects.all(),5)
    page=request.GET.get('page')
    books_list=p.get_page(page)
    pages="p"*books_list.paginator.num_pages
    context={'books':books,
    'books_list':books_list,
    'pages':pages}
    return render(request,'books/home.html',context)

def add_book(request):
    submitted=False
    if request.method =="POST":
        form =bookform(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            #return redirect('books:Home')
            return HttpResponseRedirect('/add_book?submitted=True')
    else:
        form=bookform
        if 'submitted' in request.GET:
            submitted=True
    form=bookform   
    context={'form':form,'submitted':submitted}
    #messages.info(request,("book was added successfully...."))
    return render(request,'books/add_book.html',context)

def borrowed_books(request):
    Books=Borrowed_book.objects.all()
    context={'Books':Books}
    return render(request,'books/borrowed_books.html',context)

def requested_books(request):
    books=Borrowed_book.objects.all()
    context={'books':books}
    return render(request,'books/requested_books.html',context)


def book_librarian(request, pk):
    book=Book.objects.get(id=pk)
    context = {'book': book}      
    return render(request,'books/book_librarian.html',context)

def update_book(request,id):
    book=Book.objects.get(pk=id)
    form=bookform(request.POST or None,request.FILES or None,instance=book)
    if form.is_valid():
        form.save()
        #messages.info(request,("Book updated successfully...."))
        return redirect('books:Home')
    return render(request,'books/update_book.html',
    {'book':book,
    'form':form})   

def delete_book(request,id):
    book=Book.objects.get(pk=id)
    book.delete()
    return redirect('books:Home')

def search_books_librarian(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        books=Book.objects.filter(book_title__contains=searched)
        return render(request,'books/search_books_librarian.html',
        {'searched':searched,
        'books':books})
    else:
        return render(request,'books/search_books_librarian.html')  

def Issue(request,id):
    borrowed_book = Borrowed_book.objects.get(id=id)

    return render(request,'books/view_requested_book.html',{
        'book': borrowed_book,
        'book_id': id,
    })

def Issue_book(request):
    #book=Book.objects.get(pk=id)
    form=Issue_book

#generate a pdf file of booklist
def book_report(request):
    #create bytestream buffer
    buf=io.BytesIO()
    #create canvas
    canv=canvas.Canvas(buf,pagesize=letter,bottomup=0)
    #create text object
    textob= canv.beginText()
    textob.setTextOrigin(inch,inch)
    textob.setFont("Helvetica",14)
  
    #designate model
    books=Book.objects.all()
    #blank list
    lines=[]
    for book in books:
        lines.append(book.book_title)
        lines.append(book.description)
        lines.append(book.author)
        lines.append(book.subject_area)
        lines.append("")
        
    #loop
    for line in lines:
        textob.textLine(line)

    #finish up
    canv.drawText(textob)
    canv.showPage()
    canv.save()
    buf.seek(0)

    #return response
    return FileResponse(buf,as_attachment=True,filename='report.pdf')    

books/templates/books/Issue_book.html
{% extends 'main_librarian.html'%}

{% block content%}
{% if user.is_authenticated %}

<div>
    <center>
        <h1>Add book </h1>
    <br/><br/>
    {%if submitted %}
        <div class="alert alert-primary" role="alert">
            Book was added succesfully!!! 
        </div>  
    {% else %}
        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p}} 
        <button type="submit " class="btn btn-primary">Add</button>
        </form>
    {% endif %}

    </center>


</div>
{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
{%  endblock content  %}

books/templates/books/My_books.html
{% extends 'main_students.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
<h1 style='color:blue;'>My books</h1>
{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
</div>
{% endblock content%}

books/templates/books/add_book.html
{% extends 'main_librarian.html'%}

{% block content%}
{% if user.is_authenticated %}

<div class="shadow p-4 mb-5 bg-body rounded">
    
        <h1>Add book </h1>
    <br/><br/>
    {%if submitted %}
        <div class="alert alert-primary" role="alert">
            Book was added succesfully!!! 
        </div>  
    {% else %}
        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p}} 
        <button type="submit " class="btn btn-primary">Add</button>
        </form>
    {% endif %}

    


</div>
{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
{%  endblock content  %}

books/templates/books/book_student.html
{% extends 'main_students.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1>{{book.book_title}}</h1>
    <img src="{{ book.book_cover.url }}" alt="book_cover" style="width:100px; height: 100px">
    {{ book.description }}</br>
    {{ book.author }}

    <a class="btn btn-primary" href="{% url 'books:Borrow_page' book.id %}" role="button">Borrow</a>
</div>
{% endif %}
{% endblock content%}

books/templates/books/borrowed_books.html
{% extends 'main_librarian.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1 style='color:blue;'>Borrowed books</h1>
    <div>
        {% if Books %}
            {% for book in Books %}
                <div>
                    {{ book.Book.book_cover.url }}
                    {{ book.Book.title }}
                    {{ book.Book.id }}
                    {{ book.date_borrowed }}
                    {{ book.return_date }}
                </div>
            {% endfor %}
        {% else %} 
        <h5>No books borrowed yet</h5>
        {% endif %}            
    
    </div>
    {% else %}
    <h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
    </br>
    <h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
    {% endif %}
</div>
{% endblock content %}

books/templates/books/home.html
{% extends 'main_librarian.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1 style='color:blue;'>Home page</h1>
    <div>
    
        
        <form class="d-flex" method="POST" action="{% url 'books:search_books_librarian' %}">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search books" aria-label="Search" name="searched">
             <button class="btn btn-outline-primary" type="submit">Search</button>
        </form> 
    
        <h1 class='list' style='color:blue;'>Catalogue</h1>
        <div class="row">
            {% for book in books_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ book.book_cover.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.book_title }}</h5>
                        <p class="card-text">{{ book.author }} {{ book.edition }} {{ book.publication_date }} {{ book.subject_area }}</p>
                        {% if book.description %}
                            <h5>Description:{{ book.description }}</h5>
                        {% endif %}
                    <a class="btn btn-primary" href="{% url 'books:update_book' book.id %}" role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'books:delete_book' book.id %}" role="button">Delete</a>
                </div>
            </div>
            {% endfor %}
        </div> 
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if books_list.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ books_list.previous_page_number }}">Previous</a></li>

                    {% endif %}    
       
                     <!--<li class="page-item disabled"><a class="page-link " href="#">Page {{ books_list.number }} of {{ books_list.paginator.num_pages }}</a></li>-->
                    {% for p in pages %}
                        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                    {% endfor %}

                    {% if books_list.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ books_list.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ books_list.paginator.num_pages }}">&raquo Last</a></li>

                    {% endif %}
                </ul>
            </nav>    
       
        </div>


 
    </div>


    {% else %}
    <h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
    </br>
    <h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
    {% endif %}
</div>
{% endblock content %}

books/templates/books/home_student.html
{% extends 'main_students.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1 style='color:blue;'>Home page</h1>
    <div >
    
        <form class="d-flex" method="POST" action="{% url 'books:search_books' %}">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search books" aria-label="Search" name="searched">
            <button class="btn btn-outline-primary" type="submit">Search</button>
        </form> 

        <h1 class='list' style='color:blue;'>Catalogue</h1>
       <div class="row">
            {% for book in books_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ book.book_cover.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.book_title }}</h5>
                        <p class="card-text">Author:{{ book.author }} <br/>Edition:{{ book.edition }} <br/>Date Published:{{ book.publication_date }} <br/>Subject:{{ book.subject_area }}</p>
                        {% if book.description %}
                            <h5>Description:{{ book.description }}</h5>
                        {% endif %}
                        {% if book.status == 'AVAILABLE' %}
                            <h5 class="alert alert-primary" role="alert">Status:{{ book.status }}</h5>
                        {% else %}
                            <h5 class="alert alert-danger" role="alert">Status:{{ book.status }}</h5>
                        {% endif %}
                        {% if book.status == 'AVAILABLE' %}        
                            <a class="btn btn-primary" href="{% url 'books:Borrow_page' book.id %}" role="button">Borrow</a>
                        {% endif %}
                    <a class="btn btn-success" href="{% url 'books:book_student' book.id %}" role="button">View</a>
                    
                </div>
            </div>
            {% endfor %}
       </div>
    <br/><!--
       {{ books_list }}
       <br/>
       Has Previous: {{ books_list.has_previous }}
       <br/>
       Has Next: {{ books_list.has_next }}
       <br/>
       Current Page: {{ books_list.number }}
       <br/>
       Number of pages: {{ books_list.paginator.num_pages }}
       <br/><br/><br/>-->
       <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if books_list.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ books_list.previous_page_number }}">Previous</a></li>

                {% endif %}    
       
                <!--<li class="page-item disabled"><a class="page-link " href="#">Page {{ books_list.number }} of {{ books_list.paginator.num_pages }}</a></li>-->
                {% for p in pages %}
                <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                {% endfor %}

                {% if books_list.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ books_list.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ books_list.paginator.num_pages }}">&raquo Last</a></li>

                {% endif %}
            </ul>
        </nav> 
    </div>

</div>
{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
{% endblock content %}

books/templates/books/payments_student.html
{% extends 'main_students.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1 style='color:blue;'>My payments</h1>
    {% else %}
    <h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
    </br>
    <h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
    {% endif %}
</div>
{% endblock content %}

books/templates/books/requested_books.html
{% extends 'main_librarian.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1 style='color:blue;'>Requested Books</h1>
    <div>
        {% for book in books %}
            {{ book.book }}
        </br>
            {{ book.user }}
        </br>
        <a class="btn btn-success" href="{% url 'books:view_requested_book' book.id %}" role="button">Issue Book</a>
        {% endfor %}
    </div>
    {% else %}
    <h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
    </br>
    <h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
    {% endif %}
</div>
{% endblock content %}

books/templates/books/search_books.html
{% extends 'main_students.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="container-fluid">
    <div>
        <centre>
            {% if searched %}
                <h1>
                    <div class="alert alert-primary" role="alert">
                        You searched for {{ searched }}
                    </div>  
                </h1>
                <br/>
                {% for book in books%}
                    <a href="{%url 'books:book_student' book.id %}">{{book}}</a>
                    <button class="btn btn-primary">borrow</button>
                    <br/>
                {% endfor %}
            {% else %}
                <h1>
                    <div class="alert alert-danger" role="alert">
                        Hey you forgot to search for a book..
                    </div>  
                </h1>
            {% endif %}
        </centre>
                    
        
    </div>


{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
</div>
{% endblock content %}

books/templates/books/search_books_librarian.html
{% extends 'main_librarian.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="container-fluid">
    <div>
        <centre>
            {% if searched %}
                <h1>
                    <div class="alert alert-primary" role="alert">
                        You searched for {{ searched }}
                    </div>
                
                </h1>
                <br/>
                {% for book in books%}
                    <a href="{%url 'books:book_librarian' book.id %}">{{book}}</a>
                    <a class="btn btn-primary" href="{% url 'books:update_book' book.id %}" role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'books:delete_book' book.id %}" role="button">Delete</a>
                    <br/>
                {% endfor %}
            {% else %}
                <h1>
                    <div class="alert alert-danger" role="alert">
                        Hey you forgot to search for a book..
                    </div>
                    
                </h1>
            {% endif %}
        </centre>
                    
        
    </div>


{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
</div>
{% endblock content %}

books/templates/books/update_book.html
{% extends 'main_librarian.html'%}

{% block content%}
{% if user.is_authenticated %}
<div class="shadow p-4 mb-5 bg-body rounded">
    
        <h1 style='color:blue;'>Update book</h1>
    <br/><br/>
    {%if submitted %}
    Book was updated succesfully!!!

    {% else %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p}} 
        <button type="submit " class="btn btn-primary">Update</button>
    </form>

    {% endif %}
    
    

</div>
{% else %}
<h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
</br>
<h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
{% endif %}
{%  endblock content  %}

books/templates/books/view_requested_book.html
{% extends 'main_librarian.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <h1>{{book.book_title}}</h1>
    <img src="{{ book.book_cover.url }}" alt="book_cover" style="width:100px; height: 100px">
    {{book.description}}</br>
    {{book.author}}
    <a class="btn btn-primary" href="{% url 'books:Issue_book' book.id %}" role="button">Issue</a>

    {% else %}
    <h1>Please Login First</h1> <a href="/users/login_user/" style='color:black;'>Login</a>
    </br>
    <h1>Please Signup here</h1><a href="/users/register_user/" style='color:black;'>signup</a>
    {% endif %}
</div>
{% endblock content%}

books/templates/books/welcome_page.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% csrf_token %}
     <nav style="background-color: #ffffff;">
     </nav>
     <div class="new">
     </div>
     <h1 style="color:blue;">WELCOME TO THE  CAMPUS LIBRARY</h1>
     <img src="static/images/welcome page.jpg" class="img-fluid" alt="background" background-size="cover" 
     background-attachment=""
     min-height="100vh" >
     <h2>About Us</h2>
     <p style='color:blue;'>Created by:</br>
        KYEYUNE BEN</br>
        YOKOYASI GERALD</br>
        NALUVUBI PROSCOVIA</br>
        KWEYA ANTHONY</br>
     </p>
{% endblock content %}